language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t dudckd/docker-test-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dudckd/docker-test-app npm run test
  