version: "3"
services: 
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
    
  backend:
    links: 
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports: 
      - "5000:5000"
    depends_on: 
      - mongo
    volumes:
      - /app/node_modules
      - ./server:/app

  mongo:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./mongo
    ports: 
      - "27017:27017"
